export const localization = {
  Welcome: [
    "Welcome back, ",
    "مرحبًا بك ",
    "Bienvenido de nuevo, ",
    "Bentornato, ",
  ],
  Collection: ["Collection", "مجموعة", "Colección", "Collezione"],
  Collections: ["Collections", "مجموعات", "Colecciones", "Collezioni"],
  Collection_name: [
    "Collection name",
    "اسم المجموعة",
    "Nombre de la colección",
    "Nome della collezione",
  ],
  Save: ["Save", "حفظ", "Guardar", "Salva"],
  There_is_no_collection: [
    "There is no collection",
    "لا يوجد مجموعة",
    "No hay colección",
    "Non ci sono collezioni",
  ],
  Add_a_collection: [
    "Add A Collection",
    "إضافة مجموعة",
    "Agregar una colección",
    "Aggiungi una collezione",
  ],
  Logs: ["Logs", "سجلات", "Registros", "Registri"],
  Additional_notes: [
    "Additional notes:",
    "ملاحظات إضافية:",
    "Notas adicionales:",
    "Note aggiuntive:",
  ],
  EventInfo: [
    "Event info",
    "معلومات الحدث",
    "Información del evento",
    "Informazioni sull'evento",
  ],
  EventDate: [
    "Event Date",
    "تاريخ الحدث",
    "Fecha del evento",
    "Data dell'evento",
  ],
  EventName: [
    "Event Name",
    "اسم الحدث",
    "Nombre del evento",
    "Nome dell'evento",
  ],
  Last_Added: [
    "Last Added",
    "أضيف مؤخراً",
    "Último agregado",
    "Ultimo aggiunto",
  ],
  Name_Asc: ["Name Asc", "اسم تصاعدي", "Nombre Asc", "Nome Asc"],
  Name_Desc: ["Name Desc", "اسم تنازلي", "Nombre Desc", "Nome Decr"],
  Date_Asc: ["Date Asc", "تاريخ تصاعدي", "Fecha Asce", "Data Asc"],
  Date_Desc: ["Date Desc", "تاريخ تنازلي", "Fecha Desc", "Data Decr"],
  My_closet: ["My closet", "خزانتي", "Mi armario", "Il mio armadio"],
  Outfit_Log: [
    "Outfit Log",
    "سجل الثياب",
    "Registro de atuendo",
    "Registro degli outfit",
  ],
  Season: ["Season", "الموسم", "Temporada", "Stagione"],
  Name: ["Name", "الاسم", "Nombre", "Nome"],
  Type: ["Type", "النوع", "Tipo", "Genere"],
  Fit: ["Fit", "المقاس", "Ajuste", "Veste"],
  Quantity: ["Quantity", "الكمية", "Cantidad", "Quantità"],
  Unit: ["Unit", "الوحدة", "Unidad", "Unità"],
  Size: ["Size", "الحجم", "Tamaño", "Taglia"],
  Purchase_Date: [
    "Purchase Date",
    "تاريخ الشراء",
    "Fecha de compra",
    "Data d'acquisto",
  ],
  Settings: ["Settings", "الإعدادات", "Configuración", "Configurazioni"],
  SelectItems: [
    "Select Items",
    "تحديد العناصر",
    "Seleccionar artículos",
    "Seleziona articolo",
  ],
  Next: ["Next", "التالي", "Siguiente", "Prossimo"],
  SelectAtLeastOneItem: [
    "Please select at least 1 item.",
    "يرجى تحديد ما لا يقل عن عنصر واحد.",
    "Por favor, seleccione al menos 1 artículo.",
    "Per favore seleziona almeno 1 articolo.",
  ],
  PurchaseDateAsc: [
    "Purchase Date Asc",
    "تاريخ الشراء تصاعدي",
    "Fecha de compra Asc",
    "Data d'acquisto Asc",
  ],
  PurchaseDateDesc: [
    "Purchase Date Desc",
    "تاريخ الشراء تنازلي",
    "Fecha de compra Desc",
    "Data d'acquisto Decr",
  ],
  SeasonNotSpecified: [
    "Season not specified",
    "الموسم غير محدد",
    "Temporada no especificada",
    "Stagione non specificata",
  ],
  You_can_add: [
    "You can add this Item under a collection",
    "يمكنك إضافة هذا العنصر تحت مجموعة",
    "Puedes agregar este ítem en una colección",
    "Puoi aggiungere questo articolo ad una collezione",
  ],
  Automatic_color_selection: [
    "Automatic color selection",
    "اختيار اللون التلقائي",
    "Selección de color automática",
    "Selezione automatica del colore",
  ],
  ClosetHistoryEmpty: [
    "Your closet history is empty",
    "سجل خزانتك فارغ",
    "Tu historial de armario está vacío",
    "La cronologia del tuo armadio è vuota",
  ],
  CategoryFilter: [
    "Category Filter",
    "تصفية الفئة",
    "Filtro de categoría",
    "Filtra per categoria",
  ],
  TypeFilter: [
    "Type Filter",
    "تصفية النوع",
    "Filtro de tipo",
    "Filtra per tipo",
  ],
  Pick_A_Color: [
    "Pick a color",
    "اختر لونًا",
    "Seleccionar un color",
    "Scegli un colore",
  ],
  SetBlack: ["Set Black", "تعيين الأسود", "Establecer Negro", "Imposta Nero"],
  Primary_color: [
    "Primary color",
    "اللون الرئيسي",
    "Color primario",
    "Colore primario",
  ],
  Secondary_color: [
    "Secondary color",
    "اللون الثانوي",
    "Color secundario",
    "Colore secondario",
  ],
  Tertiary_color: [
    "Tertiary color",
    "اللون الثالثي",
    "Color terciario",
    "Terzo colore",
  ],
  Adding_an_item: [
    "Adding an item",
    "إضافة عنصر",
    "Añadir un ítem",
    "Aggiungi un capo",
  ],
  EditingItem: [
    "Editing Item",
    "تحرير العنصر",
    "Editando el artículo",
    "Modifica dell'articolo",
  ],
  import_image: [
    "import image",
    "استيراد صورة",
    "Importar imagen",
    "Importa immagine",
  ],
  Use_Camera: [
    "Use Camera",
    "استخدم الكاميرا",
    "Usar la cámara",
    "Usa la fotocamera",
  ],
  import_from_device: [
    "import from device",
    "استيراد من الجهاز",
    "Importar desde el dispositivo",
    "Importa dal dispositivo",
  ],
  ThisWillRemind: [
    "This will remind you to put an item in the laundry after n number of uses.",
    "سيُذكِرك بوضع القطعة في الغسيل بعد عدد من الاستخدامات.",
    "Esto te recordará poner una prenda en la lavandería después de n usos.",
    "Questo ti ricorderà di mettere il capo in lavatrice dopo N volte di utilizzi.",
  ],
  HeatMap_description: [
    "This heatMap will show the border of the items in three colors Cyan: used within week, Yellow: used within month, Red: not used for longer than a month.",
    "ستظهر هذه الخريطة الحرارية حدود العناصر بثلاثة ألوان: الأزرق السماوي: تم استخدامها خلال الأسبوع، الأصفر: تم استخدامها خلال الشهر، الأحمر: لم يتم استخدامها لأكثر من شهر.",
    "Esta mapa de calor mostrará el borde de los elementos en tres colores: Cian: usado dentro de la semana, Amarillo: usado dentro del mes, Rojo: no usado por más de un mes.",
    "Questa mappa di calore mostrerà il bordo degli elementi in tre colori: Ciano: usato entro la settimana, Giallo: usato entro il mese, Rosso: non usato da più di un mese.",
  ],
  Reset_Image: [
    "Reset Image",
    "إعادة تعيين الصورة",
    "Restablecer imagen",
    "Reset immagine",
  ],
  Reset: ["Reset", "إعادة ضبط", "Restablecer", "Reset"],
  Close: ["Close", "إغلاق", "Cerrar", "Chiudi"],
  Delete: ["Delete", "حذف", "Borrar", "Elimina"],
  Cleaned: ["Cleaned", "تنظيف", "Limpiado", "Lavato"],
  Your_Name: ["Your Name", "اسمك", "Tu nombre", "Il tuo nome"],
  User_Name: ["Username", "اسم المستخدم", "Username", "Username"],
  Language: ["Language", "اللغة", "Idioma", "Lingua"],
  Export: ["Export", "تصدير", "Exportar", "Esporta"],
  Import: ["Import", "استيراد", "Importar", "Importa"],
  ClosetInfo: [
    "Closet Info",
    "معلومات الخزانة",
    "Armario Info",
    "Armadio Info",
  ],
  Times: ["Times", "مرات", "Veces", "Volte"],
  N: ["n", "ن", "n", "n"],
  Daily_reminder: [
    "Daily logging reminder",
    "منبه التسجيل اليومي",
    "Recordatorio diario de registro",
    "Promemoria di registrazione giornaliera",
  ],
  Enable_heatMap: [
    "Enable heatMap",
    "تفعيل الخريطة البيانية",
    "Activar mapa de calor",
    "Abilita mappa di calore",
  ],
  Laundry_reminder: [
    "Laundry reminder",
    "تذكير الغسيل",
    "Recordatorio de lavandería",
    "Ricorda di lavare dopo",
  ],
  Laundry_Options: [
    "Laundry Options",
    "خيارات الغسيل",
    "Opciones de Lavandería",
    "Opzioni lavanderia",
  ],
  Override_Laundry: [
    "Override Laundry reminder",
    "تعديل تذكير الغسيل",
    "Anular Recordatorio de Lavandería",
    "Regola il promemoria di lavaggio",
  ],
  Tops: ["Tops", "العلوي", "Tops", "Parte sopra"],
  Bottoms: ["Bottoms", "السفلي", "Parte inferior", "Parte sotto"],
  Shoes: ["Shoes", "أحذية", "Zapatos", "Scarpe"],
  Accessories: ["Accessories", "إكسسوارات", "Accesorios", "Accessori"],
  Add_New_Category: [
    "Add New Category",
    "إضافة فئة جديدة",
    "Agregar nueva categoría",
    "Aggiungi nuova categoria",
  ],
  Category_Name: [
    "Category Name",
    "اسم الفئة",
    "Nombre de la categoría",
    "Nome della categoria",
  ],
  Add_a_Category: [
    "Add A Category",
    "إضافة فئة",
    "Añadir una categoría",
    "Aggiungi categoria",
  ],
  Edit_Category: [
    "Edit Category",
    "تعديل الفئة",
    "Editar categoría",
    "Modifica categoria",
  ],
  Add_Type: ["Add Type", "إضافة نوع", "Añadir tipo", "Aggiungi tipo"],
  Add_a_new: [
    "Add a new piece of clothing",
    "إضافة قطعة ملابس جديدة",
    "Agregar una nueva prenda de vestir",
    "Aggiungi un nuovo capo di abbigliamento",
  ],
  Record_a_log: [
    "Record a log for a piece of clothing",
    "تسجيل سجل لقطعة ملابس",
    "Registrar un registro para una prenda de vestir",
    "Registra un utilizzo di un capo di abbigliamento",
  ],
  Washable: [
    "Laundry Reminder?",
    "التذكير بالغسيل؟",
    "¿Recordatorio de lavandería?",
    "Ricorda di lavare?",
  ],
  addSingleItem: [
    "Add Single Item",
    "إضافة عنصر واحد",
    "Agregar Ítem Individual",
    "Aggiungi singolo capo",
  ],
  addMultiItems: [
    "Add multiple Items",
    "إضافة عناصر متعددة",
    "Agregar Varios Ítems",
    "Aggiungi articoli multipli",
  ],
  startLocalImages: [
    "Start with Local images",
    "ابدأ بالصور المحلية",
    "Comenzar con Imágenes Locales",
    "Inizia con le immagini locali",
  ],
  startWCamera: [
    "Start with camera",
    "ابدأ بالكاميرا",
    "Comenzar con la Cámara",
    "Inizia con la fotocamera",
  ],
  bulkInfo: [
    "This will let you create items rapidly according to the number of images",
    "سيمكنك هذا من إنشاء العناصر بسرعة حسب عدد الصور",
    "Esto te permitirá crear ítems rápidamente según la cantidad de imágenes",
    "Questo ti permetterà di aggiungere capi velocemente in base al numero di immagini",
  ],
  BulkMode: ["Bulk Mode", "وضع الجملة", "Modo Masivo", "Modo Massivo"],
  Prefix: ["Prefix", "بادئة", "Prefijo", "Prefisso"],
  NumberOfItems: [
    "Number of items",
    "عدد العناصر",
    "Número de ítems",
    "Numero di capi",
  ],
  FilterByColor: [
    "Filter by color",
    "تصفية حسب اللون",
    "Filtrar por color",
    "Filtra per colore",
  ],
};

export const clothingReminderMessages = [
  [
    "Don't forget to log what you wore today!",
    "لا تنسى تسجيل ملابسك اليوم!",
    "No olvides registrar lo que llevaste hoy.",
    "Non dimenticare di registrare cosa hai indossato oggi!",
  ],
  [
    "It's time to update your outfit history.",
    "حان وقت تحديث تاريخ إطلالتك.",
    "Es hora de actualizar tu historial de atuendos.",
    "È ora di aggiornare la cronologia dei tuoi outfit.",
  ],
  [
    "Have you recorded your outfit for the day?",
    "هل قمت بتسجيل إطلالتك لليوم؟",
    "¿Has registrado tu atuendo del día?",
    "Hai registrato il tuo outfit del giorno?",
  ],
  [
    "Time to add your stylish outfit to your wardrobe.",
    "حان وقت إضافة إطلالتك الأنيقة إلى ملابسك.",
    "Es hora de agregar tu atuendo elegante a tu guardarropa.",
    "È ora di aggiungere il tuo outfit stiloso nel tuo guardaroba.",
  ],
  [
    "Remember to keep track of your fashion choices.",
    "تذكر أن تتابع اختيارات أزيائك.",
    "Recuerda llevar un registro de tus elecciones de moda.",
    "Ricorda di tenere traccia delle tue scelte fashion.",
  ],
  [
    "What did you wear today? Log it now!",
    "ماذا ارتديت اليوم؟ سجله الآن!",
    "¿Qué te pusiste hoy? ¡Regístralo ahora!",
    "Cosa hai indossato oggi? Registralo adesso!",
  ],
  [
    "Your clothing history is waiting for an update.",
    "تاريخ ملابسك في انتظار التحديث.",
    "Tu historial de ropa está esperando una actualización.",
    "La cronologia del vestiario attende di essere aggiornata.",
  ],
  [
    "It's outfit-logging time!",
    "حان وقت تسجيل الإطلالات!",
    "¡Es hora de registrar tu atuendo!",
    "È tempo di registrare l'outfit!",
  ],
];

export const clothingReminderTitles = (userName: string) => {
  return [
    [
      "Clothing Event Reminder",
      "تذكير بأحداث الملابس",
      "Recordatorio de eventos de ropa",
      "Memo degli utilizzi dei vestiti",
    ],
    [
      "Fashion Log Alert",
      "تنبيه تسجيل الأزياء",
      "Alerta de registro de moda",
      "Allerta registro Fashion",
    ],
    [
      "Wardrobe Update Reminder",
      "تذكير بتحديث الخزانة",
      "Recordatorio de actualización de armario",
      "Memo aggiornamento guardaroba",
    ],
    [
      "Outfit Logging Time",
      "وقت تسجيل الإطلالات",
      "Hora de registrar atuendos",
      "Tempo di registrare l'outfit",
    ],
    [
      "Clothing Record Notification",
      "إشعار بتسجيل الملابس",
      "Notificación de registro de ropa",
      "Notifica registrazione vestiti",
    ],
    [
      "Stay Fashionably Organized",
      "ابق منظمًا بأناقة",
      "Mantente organizado con estilo",
      "Tieni organizzato lo stile",
    ],
    [
      "Keep Your Wardrobe Updated",
      "حافظ على تحديث خزانتك",
      "Mantén tu guardarropa actualizado",
      "Tieni aggiornato il guardaroba",
    ],
    [
      "Remember to Log Your Outfit",
      "تذكر تسجيل إطلالتك",
      "Recuerda registrar tu atuendo",
      "Ricorda di registrare il tuo outfit",
    ],
    [
      `Hi ${userName}, Time to Log Your Stylish Outfit!`,
      `مرحبًا ${userName}، حان وقت تسجيل إطلالتك الأنيقة!`,
      `Hola ${userName}, ¡Es hora de registrar tu atuendo con estilo!`,
      `Ciao ${userName}, è ora di registrare il tuo stiloso outfit!`,
    ],
    [
      `Hello ${userName}, Remember to Record Your Style!`,
      `مرحبًا ${userName}، تذكّر تسجيل مظهرك!`,
      `Hola ${userName}, ¡Recuerda registrar tu estilo!`,
      `Ciao ${userName}, Ricorda di registrare il tuo stile!`,
    ],
  ];
};

const tops_en = [
  { value: "T-Shirt", label: "T-Shirt" },
  { value: "Shirt", label: "Shirt" },
  { value: "Blouse", label: "Blouse" },
  { value: "Jacket", label: "Jacket" },
  { value: "Tank Top", label: "Tank Top" },
  { value: "Polo Shirt", label: "Polo Shirt" },
  { value: "Short Sleeve Shirt", label: "Short Sleeve Shirt" },
  { value: "Peplum Top", label: "Peplum Top" },
  { value: "Sweater", label: "Sweater" },
  { value: "Turtleneck", label: "Turtleneck" },
  { value: "Hoodie", label: "Hoodie" },
  { value: "Blazer", label: "Blazer" },
  { value: "Upper Underwear", label: "Upper Underwear" },
];

const bottoms_en = [
  { value: "Trousers", label: "Trousers" },
  { value: "Jeans", label: "Jeans" },
  { value: "Shorts", label: "Shorts" },
  { value: "Joggers", label: "Joggers" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Leather Pants", label: "Leather Pants" },
  { value: "Skirt", label: "Skirt" },
  { value: "Leggings", label: "Leggings" },
  { value: "Culottes", label: "Culottes" },
  { value: "Underwear", label: "Underwear" },
];

export const accessories_en = [
  { value: "Necklace", label: "Necklace" },
  { value: "Bracelet", label: "Bracelet" },
  { value: "Ring", label: "Ring" },
  { value: "Earrings", label: "Earrings" },
  { value: "Watch", label: "Watch" },
  { value: "Handbag", label: "Handbag" },
  { value: "Clutch", label: "Clutch" },
  { value: "Backpack", label: "Backpack" },
  { value: "Belt", label: "Belt" },
  { value: "Hat", label: "Hat" },
  { value: "Scarf", label: "Scarf" },
  { value: "Gloves", label: "Gloves" },
  { value: "Sunglasses", label: "Sunglasses" },
  { value: "Tie", label: "Tie" },
  { value: "Socks", label: "Socks" },
  { value: "Headband", label: "Headband" },
  { value: "Hairpin", label: "Hairpin" },
  { value: "Hair Accessories", label: "Hair Accessories" },
];

const shoeTypes_en = [
  { value: "Sneakers", label: "Sneakers" },
  { value: "Casual Shoes", label: "Casual Shoes" },
  { value: "Sandals", label: "Sandals" },
  { value: "High Heels", label: "High Heels" },
  { value: "Boots", label: "Boots" },
  { value: "Loafers", label: "Loafers" },
  { value: "Slippers", label: "Slippers" },
  { value: "Rain Boots", label: "Rain Boots" },
  { value: "Hiking Boots", label: "Hiking Boots" },
  { value: "Running Shoes", label: "Running Shoes" },
  { value: "Dress Shoes", label: "Dress Shoes" },
  { value: "Flip-Flops", label: "Flip-Flops" },
  { value: "Winter Boots", label: "Winter Boots" },
];

const tops_ar = [
  { value: "T-Shirt", label: "تي شيرت" },
  { value: "Shirt", label: "قميص" },
  { value: "Blouse", label: "بلوزة" },
  { value: "Jacket", label: "جاكيت" },
  { value: "Tank Top", label: "تانك توب" },
  { value: "Polo Shirt", label: "قميص بولو" },
  { value: "Short Sleeve Shirt", label: "قميص أكمام قصيرة" },
  { value: "Peplum Top", label: "بلوزة بيبلم" },
  { value: "Sweater", label: "كنزة" },
  { value: "Turtleneck", label: "قلنسوة" },
  { value: "Hoodie", label: "هودي" },
  { value: "Blazer", label: "سترة رسمية" },
  { value: "Upper Underwear", label: "ملابس داخلية علوية" },
];

const bottoms_ar = [
  { value: "Trousers", label: "سراويل" },
  { value: "Jeans", label: "جينز" },
  { value: "Shorts", label: "شورت" },
  { value: "Joggers", label: "بنطلون رياضي" },
  { value: "Bermuda", label: "بيرمودا" },
  { value: "Leather Pants", label: "بنطلون جلدي" },
  { value: "Skirt", label: "تنورة" },
  { value: "Leggings", label: "بنطلون ضيق" },
  { value: "Culottes", label: "بنطلون واسع وقصير" },
  { value: "Underwear", label: "ملابس داخلية" },
];

const accessories_ar = [
  { value: "Necklace", label: "قلادة" },
  { value: "Bracelet", label: "سوار" },
  { value: "Ring", label: "خاتم" },
  { value: "Earrings", label: "أقراط" },
  { value: "Watch", label: "ساعة يد" },
  { value: "Handbag", label: "حقيبة يد" },
  { value: "Clutch", label: "محفظة يد" },
  { value: "Backpack", label: "حقيبة ظهر" },
  { value: "Belt", label: "حزام" },
  { value: "Hat", label: "قبعة" },
  { value: "Scarf", label: "وشاح" },
  { value: "Gloves", label: "قفازات" },
  { value: "Sunglasses", label: "نظارات شمسية" },
  { value: "Tie", label: "ربطة عنق" },
  { value: "Socks", label: "جوارب" },
  { value: "Headband", label: "عصابة للشعر" },
  { value: "Hairpin", label: "دبوس للشعر" },
  { value: "Hair Accessories", label: "إكسسوارات الشعر" },
];

const shoeTypes_ar = [
  { value: "Sneakers", label: "حذاء رياضي" },
  { value: "Casual Shoes", label: "حذاء عادي" },
  { value: "Sandals", label: "صندل" },
  { value: "High Heels", label: "كعب عالي" },
  { value: "Boots", label: "أحذية" },
  { value: "Loafers", label: "حذاء مسطح" },
  { value: "Slippers", label: "شبشب" },
  { value: "Rain Boots", label: "أحذية مطر" },
  { value: "Hiking Boots", label: "أحذية تسلق" },
  { value: "Running Shoes", label: "حذاء ركض" },
  { value: "Dress Shoes", label: "حذاء رسمي" },
  { value: "Flip-Flops", label: "صندل شاطئ" },
  { value: "Winter Boots", label: "أحذية شتوية" },
];

const tops_es = [
  { value: "T-Shirt", label: "Camiseta" },
  { value: "Shirt", label: "Camisa" },
  { value: "Blouse", label: "Blusa" },
  { value: "Jacket", label: "Chaqueta" },
  { value: "Tank Top", label: "Camiseta sin mangas" },
  { value: "Polo Shirt", label: "Camisa polo" },
  { value: "Short Sleeve Shirt", label: "Camisa de manga corta" },
  { value: "Peplum Top", label: "Blusa peplum" },
  { value: "Sweater", label: "Suéter" },
  { value: "Turtleneck", label: "Cuello alto" },
  { value: "Hoodie", label: "Sudadera con capucha" },
  { value: "Blazer", label: "Americana" },
  { value: "Upper Underwear", label: "Ropa interior superior" },
];

const bottoms_es = [
  { value: "Trousers", label: "Pantalones" },
  { value: "Jeans", label: "Vaqueros" },
  { value: "Shorts", label: "Pantalones cortos" },
  { value: "Joggers", label: "Pantalones deportivos" },
  { value: "Bermuda", label: "Bermudas" },
  { value: "Leather Pants", label: "Pantalones de cuero" },
  { value: "Skirt", label: "Falda" },
  { value: "Leggings", label: "Leggings" },
  { value: "Culottes", label: "Culottes" },
  { value: "Underwear", label: "Ropa interior" },
];

const accessories_es = [
  { value: "Necklace", label: "Collar" },
  { value: "Bracelet", label: "Pulsera" },
  { value: "Ring", label: "Anillo" },
  { value: "Earrings", label: "Pendientes" },
  { value: "Watch", label: "Reloj" },
  { value: "Handbag", label: "Bolso de mano" },
  { value: "Clutch", label: "Cartera de mano" },
  { value: "Backpack", label: "Mochila" },
  { value: "Belt", label: "Cinturón" },
  { value: "Hat", label: "Sombrero" },
  { value: "Scarf", label: "Bufanda" },
  { value: "Gloves", label: "Guantes" },
  { value: "Sunglasses", label: "Gafas de sol" },
  { value: "Tie", label: "Corbata" },
  { value: "Socks", label: "Calcetines" },
  { value: "Headband", label: "Diadema" },
  { value: "Hairpin", label: "Horquilla para el pelo" },
  { value: "Hair Accessories", label: "Accesorios para el pelo" },
];

const shoeTypes_es = [
  { value: "Sneakers", label: "Zapatillas" },
  { value: "Casual Shoes", label: "Zapatos casuales" },
  { value: "Sandals", label: "Sandalias" },
  { value: "High Heels", label: "Tacones altos" },
  { value: "Boots", label: "Botas" },
  { value: "Loafers", label: "Mocasines" },
  { value: "Slippers", label: "Zapatillas de casa" },
  { value: "Rain Boots", label: "Botas de lluvia" },
  { value: "Hiking Boots", label: "Botas de senderismo" },
  { value: "Running Shoes", label: "Zapatillas para correr" },
  { value: "Dress Shoes", label: "Zapatos elegantes" },
  { value: "Flip-Flops", label: "Chanclas" },
  { value: "Winter Boots", label: "Botas de invierno" },
];

const tops_it = [
  { value: "T-Shirt", label: "Maglietta" },
  { value: "Shirt", label: "Camicia" },
  { value: "Blouse", label: "Camicetta" },
  { value: "Jacket", label: "Giacchetto" },
  { value: "Tank Top", label: "Canotta" },
  { value: "Polo Shirt", label: "Polo" },
  { value: "Short Sleeve Shirt", label: "Camicia a maniche corte" },
  { value: "Peplum Top", label: "Top a balze" },
  { value: "Sweater", label: "Maglione" },
  { value: "Turtleneck", label: "Dolcevita" },
  { value: "Hoodie", label: "Felpa" },
  { value: "Blazer", label: "Blazer" },
  { value: "Upper Underwear", label: "Intimo per sopra" },
];
const bottoms_it = [
  { value: "Trousers", label: "Pantaloni" },
  { value: "Jeans", label: "Jeans" },
  { value: "Shorts", label: "Pantaloncini" },
  { value: "Joggers", label: "Tuta sportiva" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Leather Pants", label: "Pantaloni in pelle" },
  { value: "Skirt", label: "Gonna" },
  { value: "Leggings", label: "Leggings" },
  { value: "Culottes", label: "Culottes" },
  { value: "Underwear", label: "Intimo per sotto" },
];
export const accessories_it = [
  { value: "Necklace", label: "Collana" },
  { value: "Bracelet", label: "Braccialetto" },
  { value: "Ring", label: "Anello" },
  { value: "Earrings", label: "Orecchini" },
  { value: "Watch", label: "Orologio" },
  { value: "Handbag", label: "Borsa" },
  { value: "Clutch", label: "Borsetta a mano" },
  { value: "Backpack", label: "Zainetto" },
  { value: "Belt", label: "Cintura" },
  { value: "Hat", label: "Cappello" },
  { value: "Scarf", label: "Sciarpa" },
  { value: "Gloves", label: "Guanti" },
  { value: "Sunglasses", label: "Occhiali" },
  { value: "Tie", label: "Cravatta" },
  { value: "Socks", label: "Calze" },
  { value: "Headband", label: "Cerchietto" },
  { value: "Hairpin", label: "Forcina" },
  { value: "Hair Accessories", label: "Accessori per capelli" },
];
const shoeTypes_it = [
  { value: "Sneakers", label: "Sneakers" },
  { value: "Casual Shoes", label: "Scarpe Casual" },
  { value: "Sandals", label: "Sandali" },
  { value: "High Heels", label: "Tacco alto" },
  { value: "Boots", label: "Stivali" },
  { value: "Loafers", label: "Mocassini" },
  { value: "Slippers", label: "Pantofole" },
  { value: "Rain Boots", label: "Stivali da pioggia" },
  { value: "Hiking Boots", label: "Trekking" },
  { value: "Running Shoes", label: "Scarpe da corsa" },
  { value: "Dress Shoes", label: "Scarpe eleganti" },
  { value: "Flip-Flops", label: "Infradito" },
  { value: "Winter Boots", label: "Stivali invernali" },
];

export const clothesList = [
  [tops_en, bottoms_en, shoeTypes_en, accessories_en],
  [tops_ar, bottoms_ar, shoeTypes_ar, accessories_ar],
  [tops_es, bottoms_es, shoeTypes_es, accessories_es],
  [tops_it, bottoms_it, shoeTypes_it, accessories_it],
];

const closetInfo_en = [
  "Total number of clothes you have: ",
  "Total number of events: ",
  "Total number of collections: ",
  "Top 5 clothes you wore this month:",
  "Top 5 clothes you wore:",
];
const closetInfo_ar = [
  "إجمالي عدد الملابس التي لديك: ",
  "إجمالي عدد الفعاليات: ",
  "إجمالي عدد التشكيلات: ",
  "أفضل 5 ملابس قمت بارتدائها هذا الشهر:",
  "أفضل 5 ملابس قمت بارتدائها:",
];
const closetInfo_es = [
  "Número total de prendas que tienes: ",
  "Número total de eventos: ",
  "Número total de colecciones: ",
  "Top 5 prendas que usaste este mes:",
  "Top 5 prendas que usaste:",
];
const closetInfo_it = [
  "Numero totale di vestiti che hai: ",
  "Numero totale di eventi: ",
  "Numero totale di collezioni: ",
  "Top 5 vestiti che hai indossato questo mese:",
  "Top 5 vestiti che indossi:",
];

export const categoryInfo = [
  "category has:",
  "هذا الفئة تحتوي على:",
  "categoría tiene:",
  "categoria ha:",
];

export const closetInfo = [
  closetInfo_en,
  closetInfo_ar,
  closetInfo_es,
  closetInfo_it,
];
