const localization = {
    Welcome: ['Welcome', 'مرحبًا', 'Bienvenido'],
    Collection: ['Collection', 'مجموعة', 'Colección'],
    Collection_name: ['Collection name', 'اسم المجموعة', 'Nombre de la colección'],
    Save: ['Save', 'حفظ', 'Guardar'],
    There_is_no_collection: ['There is no collection', 'لا يوجد مجموعة', 'No hay colección'],
    Add_a_collection: ['Add a collection', 'إضافة مجموعة', 'Agregar una colección'],
    Logs: ['Logs', 'سجلات', 'Registros'],
    Add_a_Collection: ['Add a Collection', 'إضافة مجموعة', 'Agregar una colección'],
    Additional_notes: ['Additional notes', 'ملاحظات إضافية', 'Notas adicionales'],
    Last_Added: ['Last Added', 'آخر مضاف', 'Último agregado'],
    Name_Asc: ['Name Asc', 'اسم تصاعدي', 'Nombre Ascendente'],
    Name_Desc: ['Name Desc', 'اسم تنازلي', 'Nombre Descendente'],
    Date_Asc: ['Date Asc', 'تاريخ تصاعدي', 'Fecha Ascendente'],
    Date_Desc: ['Date Desc', 'تاريخ تنازلي', 'Fecha Descendente'],
    My_closet: ['My closet', 'خزانتي', 'Mi armario'],
    Outfit_Log: ['Outfit Log', 'سجل الزي', 'Registro de atuendo'],
    Name: ['Name', 'الاسم', 'Nombre'],
    Type: ['Type', 'النوع', 'Tipo'],
    Fit: ['Fit', 'المقاس', 'Ajuste'],
    Quantity: ['Quantity', 'الكمية', 'Cantidad'],
    Unit: ['Unit', 'الوحدة', 'Unidad'],
    Size: ['Size', 'الحجم', 'Tamaño'],
    Purchase_Date: ['Purchase Date', 'تاريخ الشراء', 'Fecha de compra'],
    You_can_add: [
      'You can add this Item under a collection',
      'يمكنك إضافة هذا العنصر تحت مجموعة',
      'Puedes agregar este ítem en una colección'
    ],
    Automatic_color_selection: ['Automatic color selection', 'اختيار اللون التلقائي', 'Selección de color automática'],
    Primary_color: ['Primary color', 'اللون الرئيسي', 'Color primario'],
    Secondary_color: ['Secondary color', 'اللون الثانوي', 'Color secundario'],
    Tertiary_color: ['Tertiary color', 'اللون الثالثي', 'Color terciario'],
    Adding_an_item: ['Adding an item', 'إضافة عنصر', 'Añadir un ítem'],
    import_image: ['import image', 'استيراد صورة', 'Importar imagen'],
    Use_Camera: ['Use Camera', 'استخدم الكاميرا', 'Usar la cámara'],
    import_from_device: ['import from device', 'استيراد من الجهاز', 'Importar desde el dispositivo'],
    Reset_Image: ['Reset Image', 'إعادة تعيين الصورة', 'Restablecer imagen'],
    Delete: ['Delete', 'حذف', 'Borrar'],
    Cleaned: ['Cleaned', 'تنظيف', 'Limpiado'],
    Your_Name: ['Your Name', 'اسمك', 'Tu nombre'],
    User_Name: ['User Name', 'اسم المستخدم', 'Nombre de usuario'],
    Language: ['Language', 'اللغة', 'Idioma'],
    Export: ['Export', 'تصدير', 'Exportar'],
    Import: ['Import', 'استيراد', 'Importar'],
    Laundry_reminder: ['Laundry reminder', 'تذكير الغسيل', 'Recordatorio de lavandería'],
    Tops: ['Tops', 'قمم', 'Tops'],
    Bottoms: ['Bottoms', 'أسفل', 'Parte inferior'],
    Shoes: ['Shoes', 'أحذية', 'Zapatos'],
    Accessories: ['Accessories', 'إكسسوارات', 'Accesorios'],
    Add_New_Category: ['Add New Category', 'إضافة فئة جديدة', 'Agregar nueva categoría'],
    Add_a_new: ['Add a new piece of clothing', 'إضافة قطعة ملابس جديدة', 'Agregar una nueva prenda de vestir'],
    Record_a_log: ['Record a log for a piece of clothing', 'تسجيل سجل لقطعة ملابس', 'Registrar un registro para una prenda de vestir'],
  };
  
  export const clothingReminderMessages = [
    ["Don't forget to log what you wore today!", "لا تنسى تسجيل ملابسك اليوم!", "No olvides registrar lo que llevaste hoy."],
    ["It's time to update your outfit history.", "حان وقت تحديث تاريخ إطلالتك.", "Es hora de actualizar tu historial de atuendos."],
    ["Have you recorded your outfit for the day?", "هل قمت بتسجيل إطلالتك لليوم؟", "¿Has registrado tu atuendo del día?"],
    ["Time to add your stylish outfit to your wardrobe.", "حان وقت إضافة إطلالتك الأنيقة إلى ملابسك.", "Es hora de agregar tu atuendo elegante a tu guardarropa."],
    ["Remember to keep track of your fashion choices.", "تذكر أن تتابع اختيارات أزيائك.", "Recuerda llevar un registro de tus elecciones de moda."],
    ["What did you wear today? Log it now!", "ماذا ارتديت اليوم؟ سجله الآن!", "¿Qué te pusiste hoy? ¡Regístralo ahora!"],
    ["Your clothing history is waiting for an update.", "تاريخ ملابسك في انتظار التحديث.", "Tu historial de ropa está esperando una actualización."],
    ["It's outfit-logging time!", "حان وقت تسجيل الإطلالات!", "¡Es hora de registrar tu atuendo!"]
  ];
  
 export const clothingReminderTitles = [
    ["Clothing Event Reminder", "تذكير بأحداث الملابس", "Recordatorio de eventos de ropa"],
    ["Fashion Log Alert", "تنبيه تسجيل الأزياء", "Alerta de registro de moda"],
    ["Wardrobe Update Reminder", "تذكير بتحديث الخزانة", "Recordatorio de actualización de armario"],
    ["Outfit Logging Time", "وقت تسجيل الإطلالات", "Hora de registrar atuendos"],
    ["Dress Record Notification", "إشعار بتسجيل الفساتين", "Notificación de registro de vestidos"],
    ["Stay Fashionably Organized", "ابق منظمًا بأناقة", "Mantente organizado con estilo"],
    ["Keep Your Wardrobe Updated", "احتفظ بخزانتك مُحدثة", "Mantén tu guardarropa actualizado"],
    ["Remember to Log Your Outfit", "تذكر تسجيل إطلالتك", "Recuerda registrar tu atuendo"]
  ];